### ISSUE TITLE
Startscreen designen

### ISSUE THREAD

**Issue by martiL** [KE-NIA/CircularitySolver#3]
AK:

- Es kann zwischen drei Trackern gewählt werden (Faro Ion, Vantage und dem virtuellen LT
- Es sind entsprechende Bilder den Button hinterlegt
- Die Bezeichnungen der Tracker (Name) stehen bei den Bildern
- Auswahl der Tracker sollte mittig platziert werden

**Comment by KE-NIA** [comment]
Wollte die comment Funktion ausprobieren! Was verstehst du unter mittig? in reihe oder untereinander?
